Akash scrum27and28
CS-3311-JDE-3346/3346-vocoder-webapp pull request #4
Opened 2024-01-22 14:10 UTC by akashmisra1

Added features to allow users to login and logout and have an account based on their google email.

2024-01-22 20:31 UTC, andrewpeng02 requested changes

2024-01-22 20:31 UTC, andrewpeng02 commented on src/app/page.tsx
> +  initFbase();
What is the point of this function if it just returns app? Can just import app directly if needed

2024-01-22 20:31 UTC, andrewpeng02 commented on src/app/page.tsx
> +          <Button onClick={signIn} className="bg-blue-700 text-slate-300">Sign In</Button>
Add padding between the buttons so they don't appear squished
<img width="407" alt="image" src="https://github.com/CS-3311-JDE-3346/3346-vocoder-webapp/assets/47485510/de54ad40-ba8a-49ab-bdcc-83263f9cddc7">

2024-01-22 20:31 UTC, andrewpeng02 commented on src/app/page.tsx
> +          <Button onClick={() => auth.signOut()} className="bg-blue-700 text-slate-300">Sign Out</Button>
If user is signed in, show sign out button; else, show sign in button

2024-01-23 22:38 UTC, akashmisra1 commented
Changes made @andrewpeng02 please check and lmk if it is ready to merge

2024-01-24 01:24 UTC, andrewpeng02 approved these changes
after resolving comments, feel free to merge

2024-01-24 01:24 UTC, andrewpeng02 commented on src/app/page.tsx
> +  app;
remove line

2024-01-24 01:24 UTC, andrewpeng02 commented on src/app/page.tsx
remove line

2024-01-24 02:06 UTC, akashmisra1 commented
Need to keep those two lines in to initialize firebase on the website. Run into error otherwise.

2024-01-24 02:06 UTC, akashmisra1 commented
Merging changes with main branch

2024-01-24 02:07 UTC, merged